package com.example.ui.post

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.example.models.Hashtag
import com.example.models.LocationTag
import com.example.models.MediaItem
import com.example.models.MediaType
import com.example.models.UserShort
import kotlinx.coroutines.delay
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.launch
import java.util.UUID

enum class UploadStatus { IDLE, PROCESSING, COMPRESSING, UPLOADING, SUCCESS, ERROR }
enum class SuggestionMode { NONE, MENTION, HASHTAG }

data class CrossPostPlatform(
    val id: String,
    val name: String,
    val enabled: Boolean
)

data class CreatePostState(
    val mediaItems: List<MediaItem> = emptyList(),
    val globalCaption: String = "",
    val aspectRatio: String = "1:1",
    val burnInCaptions: Boolean = false,
    val autoGeneratedCaptions: Boolean = false,
    val altText: String = "",
    val crossPostPlatforms: List<CrossPostPlatform> = listOf(
        CrossPostPlatform("fb", "Facebook", false),
        CrossPostPlatform("tw", "Twitter/X", false),
        CrossPostPlatform("tk", "TikTok", false)
    ),
    val uploadStatus: UploadStatus = UploadStatus.IDLE,
    val uploadProgress: Float = 0f,
    val processingMessage: String = "",
    val mentionSuggestions: List<UserShort> = emptyList(),
    val hashtagSuggestions: List<Hashtag> = emptyList(),
    val activeSuggestionMode: SuggestionMode = SuggestionMode.NONE,
    val suggestionQuery: String = "",
    val selectedLocation: LocationTag? = null,
    val locationQuery: String = "",
    val locationSuggestions: List<LocationTag> = emptyList(),
    val showLocationSearch: Boolean = false,
    val coAuthor: UserShort? = null,
    val isPaidPartnership: Boolean = false,
    val partnerBrand: UserShort? = null,
    val taggedProducts: List<com.example.models.Product> = emptyList()
)

class CreatePostViewModel : ViewModel() {
    private val _state = MutableStateFlow(CreatePostState())
    val state: StateFlow<CreatePostState> = _state.asStateFlow()

    private val mockLocations = listOf(
        LocationTag("loc1", "Eiffel Tower", "Champ de Mars, 5 Avenue Anatole France, 75007 Paris", "Landmark", 48.8584, 2.2945),
        LocationTag("loc2", "Central Park", "New York, NY", "Park", 40.7812, -73.9665),
        LocationTag("loc3", "Golden Gate Bridge", "San Francisco, CA", "Landmark", 37.8199, -122.4783),
        LocationTag("loc4", "Paris", "France", "City", 48.8566, 2.3522, isCityLevel = true),
        LocationTag("loc5", "New York", "USA", "City", 40.7128, -74.0060, isCityLevel = true)
    )

    private val mockUsers = listOf(
        UserShort("1", "natgeo", null),
        UserShort("2", "mkbhd", null),
        UserShort("3", "foodie", null),
        UserShort("4", "travel_bug", null)
    )

    private val mockHashtags = listOf(
        Hashtag("photography", 1500000, trendingScore = 95.0),
        Hashtag("nature", 2000000, trendingScore = 88.0),
        Hashtag("tech", 500000, trendingScore = 75.0),
        Hashtag("travel", 3000000, trendingScore = 92.0),
        Hashtag("lensloop", 50000, trendingScore = 99.0)
    )

    fun addMedia(uri: String, type: MediaType) {
        _state.update { 
            if (it.mediaItems.size < 10) {
                it.copy(mediaItems = it.mediaItems + MediaItem(UUID.randomUUID().toString(), uri, type))
            } else it
        }
    }

    fun removeMedia(index: Int) {
        _state.update {
            val newList = it.mediaItems.toMutableList()
            newList.removeAt(index)
            it.copy(mediaItems = newList)
        }
    }

    fun updateSlideCaption(index: Int, caption: String) {
        _state.update {
            val newList = it.mediaItems.toMutableList()
            val item = newList[index]
            newList[index] = item.copy(slideCaption = caption)
            it.copy(mediaItems = newList)
        }
    }

    fun updateGlobalCaption(caption: String) {
        if (caption.length <= 2200) {
            _state.update { it.copy(globalCaption = caption) }
            checkForSuggestions(caption)
        }
    }

    private fun checkForSuggestions(caption: String) {
        val lastWord = caption.split(Regex("\\s+")).lastOrNull() ?: ""
        when {
            lastWord.startsWith("@") && lastWord.length > 1 -> {
                val query = lastWord.substring(1)
                _state.update { it.copy(
                    activeSuggestionMode = SuggestionMode.MENTION,
                    suggestionQuery = query,
                    mentionSuggestions = mockUsers.filter { u -> u.username.contains(query, ignoreCase = true) }
                ) }
            }
            lastWord.startsWith("#") && lastWord.length > 1 -> {
                val query = lastWord.substring(1)
                _state.update { it.copy(
                    activeSuggestionMode = SuggestionMode.HASHTAG,
                    suggestionQuery = query,
                    hashtagSuggestions = mockHashtags.filter { h -> h.name.contains(query, ignoreCase = true) && !h.isBanned }.sortedByDescending { h -> h.trendingScore }
                ) }
            }
            else -> {
                _state.update { it.copy(activeSuggestionMode = SuggestionMode.NONE) }
            }
        }
    }

    fun applySuggestion(suggestion: String) {
        val words = _state.value.globalCaption.split(Regex("\\s+")).toMutableList()
        if (words.isNotEmpty()) {
            val prefix = if (_state.value.activeSuggestionMode == SuggestionMode.MENTION) "@" else "#"
            words[words.lastIndex] = "$prefix$suggestion "
        }
        _state.update { 
            it.copy(
                globalCaption = words.joinToString(" "),
                activeSuggestionMode = SuggestionMode.NONE
            )
        }
    }

    fun setAspectRatio(ratio: String) {
        _state.update { it.copy(aspectRatio = ratio) }
    }

    fun toggleBurnInCaptions(enabled: Boolean) {
        _state.update { it.copy(burnInCaptions = enabled) }
    }

    fun toggleAutoGeneratedCaptions(enabled: Boolean) {
        _state.update { it.copy(autoGeneratedCaptions = enabled) }
    }

    fun updateAltText(text: String) {
        _state.update { it.copy(altText = text) }
    }

    fun toggleCrossPost(platformId: String) {
        _state.update { state ->
            val updated = state.crossPostPlatforms.map {
                if (it.id == platformId) it.copy(enabled = !it.enabled) else it
            }
            state.copy(crossPostPlatforms = updated)
        }
    }

    fun toggleLocationSearch() {
        _state.update { it.copy(showLocationSearch = !it.showLocationSearch, locationQuery = "", locationSuggestions = emptyList()) }
    }

    fun updateLocationQuery(query: String) {
        _state.update { 
            it.copy(
                locationQuery = query,
                locationSuggestions = if (query.length > 1) {
                    mockLocations.filter { loc -> loc.name.contains(query, ignoreCase = true) || loc.address.contains(query, ignoreCase = true) }
                } else emptyList()
            ) 
        }
    }

    fun selectLocation(location: LocationTag) {
        _state.update { 
            it.copy(
                selectedLocation = location,
                showLocationSearch = false,
                locationQuery = "",
                locationSuggestions = emptyList()
            ) 
        }
    }

    fun removeLocation() {
        _state.update { it.copy(selectedLocation = null) }
    }

    fun setCoAuthor(user: UserShort?) {
        _state.update { it.copy(coAuthor = user) }
    }

    fun togglePaidPartnership() {
        _state.update { it.copy(isPaidPartnership = !it.isPaidPartnership) }
    }

    fun setPartnerBrand(brand: UserShort?) {
        _state.update { it.copy(partnerBrand = brand) }
    }

    fun addTaggedProduct(product: com.example.models.Product) {
        _state.update { 
            if (it.taggedProducts.size < 5 && !it.taggedProducts.contains(product)) {
                it.copy(taggedProducts = it.taggedProducts + product)
            } else it
        }
    }

    fun removeTaggedProduct(product: com.example.models.Product) {
        _state.update { it.copy(taggedProducts = it.taggedProducts - product) }
    }

    fun submitPost() {
        if (_state.value.mediaItems.isEmpty()) return

        viewModelScope.launch {
            val hasVideo = _state.value.mediaItems.any { it.type == MediaType.VIDEO }
            
            if (hasVideo) {
                _state.update { it.copy(uploadStatus = UploadStatus.PROCESSING, processingMessage = "Transcoding video (1080p, 720p, 480p) and extracting thumbnails...") }
                delay(1500)
            }

            _state.update { it.copy(uploadStatus = UploadStatus.COMPRESSING, processingMessage = "Compressing media maintaining quality (SSIM > 0.95)...") }
            delay(1000) 
            
            _state.update { it.copy(uploadStatus = UploadStatus.UPLOADING, uploadProgress = 0f, processingMessage = "Uploading to multi-region CDN...") }
            for (i in 1..10) {
                delay(200) 
                _state.update { it.copy(uploadProgress = i / 10f) }
            }
            
            _state.update { it.copy(uploadStatus = UploadStatus.SUCCESS, processingMessage = "Shared!") }
            delay(1000)
            _state.update { CreatePostState() }
        }
    }
}
